### ISSUE TITLE
Design 'By Company' Page

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#10]
To provide rough sketch of By Company Page in order to inform  what needs to done from a frontend and backend side to enable users to search by Company for all IOLs in the database.

**Comment by ButtercupUltra** [comment]
I think its just the chance to have all IOLs of that company under a single page.
ie

Alcon
-sn60wf
-sn6at
etc etc etc

each one of those lenses could have a link for their own IOL page

**Comment by medic-code** [comment]
Thanks! 

It was just in case you had specific designs for how you wanted it to look. Happy to do the designing, but want to give you first pass as you're both a developer and a potential user at the same time!

**Comment by medic-code** [comment]
This has now been designed!
