### ISSUE TITLE
Create IOL Assist Icon

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#13]
Design and Create the IOL Assist Icon to be used when installing the mobile app.

**Comment by ButtercupUltra** [comment]
Suggest:   there is a circle with a checkered background whenever you open obe of your design apps.  i like that template, we could add a one piece iol in front.

**Comment by medic-code** [comment]
This has been designed by Katy! Will close as I've added to backlog on monday.com.
