### ISSUE TITLE
Design 'By Scenario' Page

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#16]
Design the 'By Scenario' Page to inform choices of the frontend and backend.

**Comment by medic-code** [comment]
As per discussion, leave open for now but note to refrain from adding features that influence clinical decision making at the present

**Comment by ButtercupUltra** [comment]
Perhaps this will be omitted, to avoid medical device or decision making issues...

**Comment by medic-code** [comment]
Close for now as clinical guidance offering
