### ISSUE TITLE
Design 'Sulcus Change' page

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#17]
Design 'Sulcus Change' Page to inform the frontend and backend of Sulcus change page.

**Comment by ButtercupUltra** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="1894.6">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px 'Helvetica Neue'; min-height: 14.0px}
p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; text-align: center; font: 12.0px 'Helvetica Neue'}
table.t1 {border-collapse: collapse}
td.td1 {border-style: solid; border-width: 1.0px 1.0px 1.0px 1.0px; border-color: #9a9a9a #9a9a9a #9a9a9a #9a9a9a; padding: 1.0px 5.0px 1.0px 5.0px}
</style>
</head>
<body>
<p class="p1"><br></p>


Power at Capsular Bag | Power at Ciliary Sulcus | Bag / Sulcus Difference | Subtract from Bag Power
-- | -- | -- | --
+30.00 D | +28.55 D | -1.45 D | -1.50 D
+29.50 D | +28.09 D | -1.42 D | -1.50 D
+29.00 D | +27.61 D | -1.39 D | -1.50 D
+28.50 D | +27.14 D | -1.36 D | -1.50 D
+28.00 D | +26.67 D | -1.33 D | -1.00 D
+27.50 D | +26.20 D | -1.30 D | -1.00 D
+27.00 D | +25.73 D | -1.27 D | -1.00 D
+26.50 D | +25.26 D | -1.25 D | -1.00 D
+26.00 D | +24.79 D | -1.22 D | -1.00 D
+25.50 D | +24.31 D | -1.19 D | -1.00 D
+25.00 D | +23.84 D | -1.16 D | -1.00 D
+24.50 D | +23.36 D | -1.13 D | -1.00 D
+24.00 D | +22.89 D | -1.11 D | -1.00 D
+23.50 D | +22.42 D | -1.08 D | -1.00 D
+23.00 D | +21.94 D | -1.05 D | -1.00 D
+22.50 D | +21.47 D | -1.03 D | -1.00 D
+22.00 D | +21.00 D | -1.00 D | -1.00 D
+21.50 D | +20.53 D | -0.97 D | -1.00 D
+21.00 D | +20.05 D | -0.95 D | -1.00 D
+20.50 D | +19.58 D | -0.92 D | -1.00 D
+20.00 D | +19.11 D | -0.89 D | -1.00 D
+19.50 D | +18.63 D | -0.87 D | -1.00 D
+19.00 D | +18.16 D | -0.84 D | -1.00 D
+18.50 D | +17.69 D | -0.82 D | -1.00 D
+18.00 D | +17.21 D | -0.79 D | -1.00 D
+17.50 D | +16.73 D | -0.77 D | -1.00 D
+17.00 D | +16.26 D | -0.74 D | -0.50 D
+16.50 D | +15.78 D | -0.72 D | -0.50 D
+16.00 D | +15.31 D | -0.69 D | -0.50 D
+15.50 D | +14.83 D | -0.67 D | -0.50 D
+15.00 D | +14.35 D | -0.64 D | -0.50 D
+14.50 D | +13.88 D | -0.62 D | -0.50 D
+14.00 D | +13.40 D | -0.60 D | -0.50 D
+13.50 D | +12.93 D | -0.57 D | -0.50 D
+13.00 D | +12.45 D | -0.55 D | -0.50 D
+12.50 D | +11.97 D | -0.53 D | -0.50 D
+12.00 D | +11.49 D | -0.50 D | -0.50 D
+11.50 D | +11.02 D | -0.48 D | -0.50 D
+11.00 D | +10.54 D | -0.46 D | -0.50 D
+10.50 D | +10.07 D | -0.43 D | -0.50 D
+10.00 D | +9.58 D | -0.41 D | -0.50 D
+9.50 D | +9.11 D | -0.39 D | -0.50 D
+9.00 D | +8.63 D | -0.37 D | No Change
+8.50 D | +8.16 D | -0.35 D | No Change
+8.00 D | +7.68 D | -0.32 D | No Change
+7.50 D | +7.20 D | -0.30 D | No Change
+7.00 D | +6.72 D | -0.28 D | No Change
+6.50 D | +6.24 D | -0.26 D | No Change
+6.00 D | +5.76 D | -0.24 D | No Change
+5.50 D | +5.28 D | -0.22 D | No Change
+5.00 D | +4.81 D | -0.20 D | No Change


</body>
</html>

**Comment by ButtercupUltra** [comment]
this is a generic to sulcus iol change which is used in Fife.  don't have the reference yet, but that can help with creating the carrousel

**Comment by medic-code** [comment]
Ha you might have to explain this to me I think... Would we have to make
any mathematical changes, or it is a case of displaying this information in
a carousel?

Might be better to jump on a call about this perhaps. No urgency yet though.

**Comment by ButtercupUltra** [comment]
I think there will need to be a mathematical change for other lenses.  This should be from Sa 3 piece IOL in the bag to one in sulcus.  We normally dont calculate for 3 pieces.  That is precisely part of the mixup and what makes this function so attractive.

**Comment by medic-code** [comment]
Think I probably need to have a bit more knowledge about the clinical aspects of this - If we have to figure something out mathematically this is gonna require some digging - Lets save this for a discussion for the theh future for now.

**Comment by ButtercupUltra** [comment]
Some literature and aspects to help justify the app and the sulcus carrousel.


**Cataract surgery is one of the most routine operations in health care worldwide, with approximately 17·7 million procedures performed in 2018.**

Market Scope. 2019 cataract surgical equipment market report: a global analysis for 2018 to 2024. May, 2019. https://www.marketscope.com/pages/reports/101/2019-cataract-surgical-equipmentmarket-report-a-global-analysis-for-2018-to-2024-may-2019#reports

**The French Technical Agency for Information on Hospitalisation reported a 21·9% increase in these procedures in the period 2010 - 2016.  This trend is observed worldwide as global age rises alongside life-expectancy.**

ScanSanté. Programme national de chirurgie ambulatoire: indicateurs par spécialité. June, 2015. https://www.scansante.fr/sites/ default/files/content/271/notice_chirurgie_ambulatoire_specialite.pdf 


**Despite advances in surgical techniques and technology, intraoperative complications still occur, with posterior capsule tears as the most common serious complication .** 

Desai P, Minassian DC, Reidy A. National cataract surgery survey 1997-8: a report of the results of the clinical outcomes. Br J Ophthalmol 1999;83(12):1336–1340. 

Zaidi FH, Corbett MC, Burton BJ, Bloom PA. Raising the benchmark for the 21st century–the 1000 cataract operations audit and survey: outcomes, consultant-supervised training and sourcing NHS choice. Br J Ophthalmol 2007;91(6): 731–736.


**Perioperative complications can affect 4·2% to 8·6% of eyes operated on, and are associated with worse postoperative visual outcomes.**

Day AC, Donachie PH, Sparrow JM, Johnston RL. The Royal College of Ophthalmologists’ National Ophthalmology Database study of cataract surgery: report 1, visual outcomes and complications. Eye (Lond) 2015; 29: 552–60.

Zaidi FH, Corbett MC, Burton BJ, Bloom PA. Raising the benchmark for the 21st century–the 1000 cataract operations audit and survey: outcomes, consultant-supervised training and sourcing NHS choice. Br J Ophthalmol 2007;91(6): 731–736.


**Placement of a 3-piece IOL in the ciliary sulcus is a common treatment option for posterior capsule rupture.**

Wagoner MD, Cox TA, Ariyasu RG, Jacobs DS, Karp CL, American Academy of Ophthalmology. Intraocular lens implantation in the absence of capsular support: a report by the American Academy of Ophthalmology. Ophthalmology 2003;110(4):840–859. 


**The lens position of the sulcus-implanted IOL is different than that of the predicted one for the in-the-bag IOL. When placing a sulcus-implanted IOL, it needs less power to achieve a similar postoperative refraction when compared to its in-the-bag coutnerpart. Previous studies have shown that a reduced sulcus-implanted IOL power can provide better refractive outcomes than IOL power for in-the-bag implantation.** 

Suto C, Hori S, Fukuyama E, Akura J. Adjusting intraocular lens power for sulcus fixation. J Cataract Refract Surg 2003; 29(10):1913–1917.

Eom Y, Song JS, Kim HM. Modified Haigis Formula Effective Lens Position Equation for Ciliary Sulcus-Implanted Intraocular Lenses. Am J Ophthalmol. 2016 Jan;161:142-49.e1-2. doi: 10.1016/j.ajo.2015.09.040. Epub 2015 Oct 9. PMID: 26456253

**The postoperative refraction of eyes with sulcus-implanted IOLs is usually roughly estimated by reducing the IOL power at the surgeon’s discretion. Generally, surgeons will empirically subtract 0.50 to 1.50 diopters from the IOL power calculated for the in-the-bag calculation.** 

Suto C, Hori S, Fukuyama E, Akura J. Adjusting intraocular lens power for sulcus fixation. J Cataract Refract Surg 2003; 29(10):1913–1917.

**Recent audit at a centre in NHS England shower only 20% of lenses selected for sulcus implantation after an operative complication were adequate.**  

Khan S, Mamtora S, Mohammed S, Ferris J. 
How good are we at choosing the correct three-piece intraocular lens in patients with posterior capsular rupture? Presented in poster format during RCOphth Annual Congress 2021. https://epostersonline.com/rco2021/node/78?view=true

**Comment by ButtercupUltra** [comment]
add


7·0% to 16·2% of eyes have a postoperative absolute refraction error of more than 1 dioptre greater than planned preoperatively. This is due to a wide range of reasons, including the use of non-optimised A constants, differences in biometry devices, and characteristics of the eye to be operated upon. 

Gale RP, Saldana M, Johnston RL, Zuberbuhler B, McKibbin M. Benchmark standards for refractive outcomes after NHS cataract surgery. Eye (Lond) 2009; 23: 149–52. 
 
Lundstrom M, Dickman M, Henry Y, et al. Risk factors for refractive error after cataract surgery: analysis of 282 811 cataract extractions reported to the European registry of quality outcomes for cataract and refractive surgery. J Cataract Refract Surg 2018; 44: 447–52

Bourne RRA, Stevens GA, White RA, et al. Causes of vision loss worldwide, 1990–2010: a systematic analysis. Lancet Glob Health 2013; 1: e339–49.

**Comment by medic-code** [comment]
Some great content here and perhaps best in another ticket about the business and clinical case of the app. Will move this content over to that. 

Otherwise I've designed the sulcus change page now.
