### ISSUE TITLE
Confirm order of carousels for len spec and optimized IOL Constants

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#2]
After discussion,

Confirm data for each part of the carousel is in the best order for the user.

**Comment by medic-code** [comment]
Order of carousels currently on app. 

**Lens Specification**
1. Haptic Material
2. Optic Material
3. Design 
4. Range
5. Steps
6. Optical Diameter
7. Overall length
8. Haptic Angle 

**Optimized IOL Constants**
1. Nominal
2. Haigis
3. Hoffer Q
4. Holl.1
5. SRK/T
6. SRK II

**Comment by ButtercupUltra** [comment]
Name:   Acrysof SN60WF

**Lens Specification**

Brand: Alcon ...
Design
Range
Steps
Material
Haptic Material
Optic Material
Optical Diameter
Overall length
Cartridge
Inyector

**CONSTANTS**
Nominal
SRK/T
SRK II
Hoffer Q
Barrett
Haigis
Holladay 1

**Comment by medic-code** [comment]
Thanks Juan!

For single piece lens I'm presuming we would just display material rather than haptic and optic material ? 

What are cartridge and Inyector ? Do I need to add them to the database as a field for all lens ? 

I'm presuming for barret we need to aspire towards having barrett constants for all lens  ?

**Comment by medic-code** [comment]
Just a note to say I've added cartridge and inyector to the database fields and the form.

**Comment by medic-code** [comment]
Just to confirm what was discussed via text.

1. Remove haptic angle from carousel

2. Brand in the carousel ? Or just have it the brand displaye as 'Brand Lens name' on the Title of the IOL page ? Would save on space in the carousel. Or would you prefer 'Lens Name' as the title of the IOL page only and provide brand in the carousel ?

3. Not to include RFNB 

4. Haptic and Optic material only for 3 piece lens, material for one piece lens. 

5. Barret to be included in all lens.

**Comment by ButtercupUltra** [comment]
1.  Yes, remove haptic angle.  Doesn’t really provide much clinical relevance.
2. I don’t think the brand name makes much sense in the carrousel.  We could have it in small font over the Lens Name on the Title of the IOL Page.  Example

Alcon
SN60WF

Info
Info
CARROUSEL

If that makes sense?

3. Not include that one
4. Yes
5. Yes.  It should read:

Barret (Lens factor)… would need to see how to style it. Like Haggis has a0, a1 & a2, Barret has lf (lens factor).  This can be confusing.  We can discuss it further.

I still can’t open the project in expo.  Does that mean we can only do it at home?

**Comment by medic-code** [comment]
1. Will update the database and form to reflect that 
2. Yep I agree. Will make sure that the IOL page reflects that. 
3. Yep
4. Yep
5. Okay! Yep let me know how it should be styled, I'd added the field in the database anyways.

Yes unfortunately can only do it at home, as it's a local webserver run on my laptop. It's on my list of priorities to get it setup online. Will try look into it today, I managed to do what I thought was necessary, so may just be some small thing to correct to get the server up.

**Comment by medic-code** [comment]
I'm closing this issue as I think we had the correct order ? But we need to just review the app screen as it stands as it's been quite a few months.
