### ISSUE TITLE
Style the Home page boxes

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#34]
Look abit amateurish, needs a rethink how to display this.

**Comment by ButtercupUltra** [comment]
Can't see the app, and I no longer share your wifi... Yeah, that is something we might have to take a look at!

**Comment by medic-code** [comment]
I think I know how to design this abit better now. But I’ll probably want
to put the design up on Figma which is a piece of software for design that
anyone can access online so you can feedback on design choices. At the
moment we don’t have consistent styling and that will effect the aesthetics
as well as the code I’ve written. So leave the design changes for now. If
you have design ideas for the other aspects of the app other than the home
page and lens page - scribble them down on paper or something you feel
comfortable with and I will incorporate in Figma. I want to be more
intentioned when it comes to the design of it.

**Comment by medic-code** [comment]
This has been done.
