### ISSUE TITLE
Add ULIB link to additional information 

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#37]

**Comment by ButtercupUltra** [comment]
http://ocusoft.de/ulib/c1.htm

Barret is not mentioned in ulib.  Barret is RELATIVELY new, perhaps the database was compiled before barret and RFNB, which is another formula.

**Comment by medic-code** [comment]
Thanks!

**Comment by medic-code** [comment]
Added the ULIB link to the iol pages.
