### ISSUE TITLE
Description of use case for IOL Assist 

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#39]
In order to have the IOL Assist on the App store we will need to outline a use case description for the users, to entice and to inform them about the product. Would also be useful for the Github Repo!

**Comment by ButtercupUltra** [comment]
_IOL Assist_ is the best mobile app to contribute reference points and tips for the best choice in intraocular lens implantations in your practice.  Whether you are an experienced ophthalmologist, an optometrist, orthoptist, technician, or specialist trainee or resident, having _IOL Assist_ ready can streamline your calculations and point you to the right direction.  This is a handy tool for determining the best alternatives for IOL selection, as well as readily accessing data specific to each lens in the market. Eye care professionals can also benefit from other useful tools, such as quick reference for sulcus implantation, determining best size of capsular tension rings, and verifying the material of a particular IOL. 

_IOL Assist_ provides direct links to the official lens websites for a more in-depth read, as well as links to the most up-to-date constant databases. 

_IOL Assist_ provides a frills-free, straight-forward reference to IOL details for everyday practice.  This is an invaluable tool for those with a wide selection of lenses in their disposable and those wanting to hone their skills to provide the best possible refractive outcome.

**Comment by medic-code** [comment]
Love this Juan! Just a few suggestions.

**IOL Assist is the best mobile app for looking up intraocular lens data and supporting you on the best choice in intraocular lens implantations in your practice**. 

Whether you are an experienced ophthalmologist, an optometrist, orthoptist, technician, or specialist trainee or resident, having IOL Assist ready can streamline your calculations and point you **in** the right direction. This is a handy tool for determining the best alternatives for IOL selection, as well as readily accessing data specific to each lens in the market. 

Eye care professionals can also benefit from other useful tools, such as quick reference for sulcus implantation, **determining the best** size of capsular tension rings, and verifying the material of a particular IOL.

IOL Assist provides direct links to the official lens websites for a more in-depth read, as well as links to the most up-to-date constant databases.

IOL Assist provides a **no-frills**, straight-forward reference to IOL details for everyday practice. This is an invaluable tool for those with a wide selection of lenses in their disposable and those wanting to hone their skills to provide the best possible refractive outcome.

**Comment by ButtercupUltra** [comment]
**IOL Assist is the best mobile app for reviewing intraocular lens data and supporting you in your practice.**

Whether you are an experienced ophthalmologist, an optometrist, technician, or specialist trainee, _IOL Assist_ ready can streamline your calculations and point you in the right direction when choosing intraocular lenses. This is a handy tool for determining the best alternatives for IOL selection, as well as readily accessing data specific to each lens in the market.

Eye care professionals can also benefit from other useful tools, such as quick reference for sulcus implantation, details on viscoelastics, determining the size of capsular tension rings, choosing best cartridges for imlantation, and verifying the material of particular IOLs.

_IOL Assist_ provides direct links to the official lens websites for a more in-depth read, as well as links to the most up-to-date databases.

_IOL Assist_ provides a **no-frills**, **straight-forward** reference to IOL details for everyday practice. This is an invaluable tool for those with a wide selection of lenses at their disposal and those wanting to provide the best possible refractive outcome.

**Comment by medic-code** [comment]
IOL Assist is the best mobile app for reviewing intraocular lens data and supporting you in your practice.

Whether you are an experienced ophthalmologist, an optometrist, technician, or specialist trainee, IOL Assist ready can streamline your calculations and point you in the right direction when choosing intraocular lenses. This is a handy tool for determining the best alternatives for IOL selection, as well as readily accessing data specific to each lens in the market.

Eye care professionals can also benefit from other useful tools, such as quick reference for sulcus implantation, details on viscoelastics, determining the size of capsular tension rings, **choosing the best** cartridges for **implantation**, and verifying the material of particular IOLs.

IOL Assist provides direct links to the official lens websites for a more in-depth read, as well as links to the most up-to-date databases.

IOL Assist provides a no-frills, straight-forward reference to IOL details for everyday practice. This is an invaluable tool for those with a wide selection of lenses at their disposal and those wanting to provide the best possible refractive outcome.

**Comment by medic-code** [comment]
Closing this issue for now, but can be editted in future.
