### ISSUE TITLE
Confirm data for individual IOL page

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#4]
To confirm that the level of information for the individual IOL page is correct and doesn't require changing. This is important if we need to make changes to the database fields for the IOLs prior to scaling up the number of IOLs in the database.

**Comment by medic-code** [comment]
See https://limitless-brushlands-87925.herokuapp.com/ for the fields that are used to collect the data to be used on the individual IOL page.

**Comment by ButtercupUltra** [comment]
Add 
Brand or Commercial House or COmpany or something of the sorts so it can eaily be filtered by the search bar. That way, all Alcon lenses can be identified, versus all Zeiss or AMO etc etc

**Comment by medic-code** [comment]
Currently when searching for the lens, when a user types whatever it's checking if its in the lens name that is currently stored in the database. The lens name in the database has the brand first prior to the more specific part of the lens. So should account for all alcon lens etc... when typing alcon into the search bar.

However consisder if you want in the database 'brand' and 'lens name' separately. The problem may be is that the search bar has to look at one field in the database for the information to find the lens. We probably want to include both brand and lens name in one field, as if the user searchs for either, the lens will pop up. So a specific lens name is typed in, that specific lens should show up. However, if the person types 'alcon' it should show up all alcon lens.

**Comment by medic-code** [comment]
Discussed in person about being happy with data for each IOL now. Discussed how to visualise brand in other issue.
