### ISSUE TITLE
Add cartridge and inyector to spreadsheet data for Alcon lens.

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#51]

**Comment by ButtercupUltra** [comment]
Where can I access the spreadsheet data?  Don't want to write it down in some other spreadsheet and then have duplicates around.

**Comment by medic-code** [comment]
Its the spreadsheet you sent me a while back. Will resend via your gmail
address.

**Comment by ButtercupUltra** [comment]
Mmmmm perhaps catridges are too Alcon-centric?  Lets let this sit for a while. Not priority.

**Comment by medic-code** [comment]
No worries lets keep this in the back log

**Comment by medic-code** [comment]
I've added this to monday.com so will close.
