### ISSUE TITLE
Decide when we are happy with minimal viable product 

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#54]
Need to discuss when we are happy with a minimal viable product to get users to do beta testing. We should probably do this sooner rather than later. The more features we add, the more technical and clinical debt we will acquire and less chance we get valuable feedback. I'd rather several rounds of beta testing and make changes incrementally than spending weeks implementing changes and then only testing once. Have to have a balance though because people will not necessarily want to do several rounds of beta testing. 

We could ask some people who would be open to doing several iterative beta testing and feedback prior to a bigger release to the rest of the beta testers.

**Comment by ButtercupUltra** [comment]
I imagine:
1. Have all Alcon lenses in
2. Have most common Zeiss lenses
3. Have the iol logos and search queries and links to external
4. have links to calculators 
5. have sulcus change carrousel

this should be the minimal, i think.  it would allow work to be done at a busy clinic

**Comment by medic-code** [comment]
Okay. Let's work towards that as the goals.

**Comment by medic-code** [comment]
Just looking at your list again. @ButtercupUltra 

Any chance you can expand on search queries ? Are we talking about 'By Company' 'By Type'  ? 

By links to external -> ULIB and official product data I presume ?

Just to clarify the home page. After we have all the alcon lens, most common zeis lens in the database, we should have the ability to search By company and search by Type ? Then have a link to a sulcus change carousel ? Specifically drop 'By Scenario' for the present. 

With regard to calculators - no plans to create our on calcs at present, but just links to other calculators ?

**Comment by medic-code** [comment]
@ButtercupUltra Could you just clarify the above now that time has past a bit ? I'll close the issue after that

**Comment by ButtercupUltra** [comment]
Re:

Have all Alcon lenses in
Have two Zeiss lenses for diversity sake
Have the iol logos and links to external official sites (Alcon)
Have search queries for Alcon lenses and those two Zeiss. The queries should be by model of the lens, and another by company
Have links to calculators. The ones I sent last time should be more than enough.
have sulcus change carrousel with the table I provided.  This would need to change in the future, as it is possible there would be changes according to the lens (math needs to be worked out; not now)

this should be the minimal. I think with that we could show it off to IOL Con.

**Comment by medic-code** [comment]
Okay I will close this issue and I think that’s a fine list to start with.
