### ISSUE TITLE
Provide links for calculators

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#57]
Noted in the Minimal viable product discussion, but just an issue to add the links to the calcs here so I can use them.

**Comment by medic-code** [comment]
@ButtercupUltra

**Comment by ButtercupUltra** [comment]
Barret Universal IOL Formula
https://calc.apacrs.org/barrett_universal2105/

Barret Toric Calculator
https://ascrs.org/tools/barrett-toric-calculator/

EyeCalc. SRK-T
http://eyecalc.org/srk-t/

Doctor Hill.  Multiple.  Amazing Site
https://doctor-hill.com/iol-main/iol_main.htm

Hill-RBF Calculator
https://rbfcalculator.com/online/index.html

These are only some. But pretty much the only ones I ever use.  There is another for post-refractive, but thats too complicated for the aims of the app.

**Comment by medic-code** [comment]
Thanks for these

Need to design a way to display these which makes some sense.
