### ISSUE TITLE
Input Viscoelastics information for lens into form

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#59]
Input viscoelastics information into the form when it's been created and the database has been setup

**Comment by medic-code** [comment]
When database and form are created, to input the data into the form for viscoelastics.

**Comment by medic-code** [comment]
@ButtercupUltra

**Comment by medic-code** [comment]
Start off with one viscoelastic so we can prototype what it will look like on the screen.

**Comment by ButtercupUltra** [comment]
Here's three.  All Alcon:

ALCON

**Viscoat**
/ Classification /
Dispersive (yellow)

/ Components /   
3% Sodium Hyaluronate 
4% Chondroitin Sulfate

https://professional.myalcon.com/cataract-surgery/cataract-disposables/ovds/

ALCON

**ProVisc**
/ Classification /
Cohesive (green)

/ Components /   
1% Sodium Hyaluronate 

https://professional.myalcon.com/cataract-surgery/cataract-disposables/ovds/


ALCON

**DisCoVisc**
/ Classification /
Dispersive (yellow)

/ Components /   
1.65% Sodium Hyaluronate 
4% Chondroitin Sulfate

https://professional.myalcon.com/cataract-surgery/cataract-disposables/ovds/

**Comment by medic-code** [comment]
I've copeid this to monday.com so will close this.
