### ISSUE TITLE
Confirm how we want viscoelastics information display

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#60]
Confirm how you want the viscoelastics information to be displayed. Happy to discuss in person if easier than commenting.

**Comment by medic-code** [comment]
Discussed - Similar to IOL page with carousel, but with a similar viscoelastic feature -> link to the individual viscoelastic page for the similar item. 

Additional information: 
Link to individual viscoelastic page.

**Comment by medic-code** [comment]
@ButtercupUltra

**Comment by ButtercupUltra** [comment]
Yes.  The data of viscolaestic will be minimal.  
Basically:
1) cohesive, dispersive, or a combination of both (viscoadaptative or viscodispersive) (Color icons for this)
2) its basic components and concentration (most are a combination of sodium hialuronate and condrointin sulfate)

And thats that!

**Comment by medic-code** [comment]
Thanks for this. 

I see you've provided three examples which helps clarify what we want displayed. Needs a design though but can do this later.

**Comment by medic-code** [comment]
I've copied to monday.com and will close issue.
