### ISSUE TITLE
Clarify images used in google and copyright 

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#67]
To ensure no copyright issues clarify images found in google and necessary to check the website where the images are from. Check the terms and conditions/license found on the website. Will usually tell you if it's in public domain or not. 

@ButtercupUltra

**Comment by ButtercupUltra** [comment]
is this for the IOL icons?  mmmm, no clue as to where I got them.  i guess the easiest thing would do another search for them and note down the url instead of just the image. ill try that

**Comment by medic-code** [comment]
Yep, no rush, but just need to clarify if they are in the public domain.
Most websites will have a terms and conditions. If not, can ask Katy to
draw them.

**Comment by ButtercupUltra** [comment]
IOL Con uses the iol images from the manufacturers.  Is this it? They right in their terms of use, section 8, Rights of Use:

Business brands and logos of Users may be used by Steinbeis for referencing purposes,
but may not be redesigned or publicly disseminated.

**Comment by medic-code** [comment]
Do they not mean brands and logos by users of their website who upload those images ? 

Similar sort of thing with data - if we use iol images from manufacturers, we would need to ask permission to use it. I had in my brain that the images just give reference to the type of lens and not different images from different specific lens - is this correct ? If so drawing them ourselves wouldn't be too hard and gets around the copyright issue.

**Comment by medic-code** [comment]
I've added this information to monday.com, will close.
