### ISSUE TITLE
Copyright / Legal issues

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#68]
@ButtercupUltra 
1. **Copyright issues** 

Source of data and data usage considerations 

 
 _Terms and Conditions_ 
 
1. Lens -navi 
There's a german app called 'Lens - navi' that does something similar. You have to pay for it to use it though, so can't comment on details. 
Section 13 of https://www.app4eyes.com/privacypolicy/ is very interesting. It seems to suggest we can use the data as long as we say companies can get in contact with us to tell us to remove their information. Rather than proactively asking them. We should confirm this with some guidance from a lawyer though as don't want to be on the wrong side of it.

2. IOL Con

IOL Con has an interesting Terms and conditions document that we need to look carefully at. 

https://iolcon.org/termsOfUse.php

Particularly Section 8, 10 and 11. From my quick reading it seems we may not be able to use this data... Or at the very least we'll have to have a conversation with Steinbeis.

3. _ULIB Website_

I can't see any terms or conditions on this website. Wolfgang Haigis PhD, Inst. for Ophthalmic Biometry, Wuerzburg, Germany (wh@ocucalc.de) apparently maintains this list and probably need to contact him to ask for permission to use the data or atleast query him as to who we would need permission from to use the data. 

Contact info for Steinbeis Transfer Center - Vision Researchwho maintains this list -  admin@iolcon.org

**Potential Solutions** 

- Asking the lens manufacturers directly (Most will say no I would imagine)

- To consult copyright lawyer on whether something like what Lens-navi does to be okay (ie, if companies get wind, will remove data, but do this reactively and NOT pro-actively, bit more uncomfortable about this idea)

- Alternative sources of data. If it's research related ones, then we probably have to seek the permission from individual authors to use their data, probably with the provisor of providing a reference to the source on the app. 

2. **Intellectual property** 

Something to inquire about with regard to the App. My gut tells me this may be less of a concern, there's only one direct competitor that I can see. I'm not sure what the crossover between IP and software development is. When to file for patent. I think firstly we need to be sure we can use the data. 

3. **Data Protection** 

May need to have a disclaimer about patient data not being used or personal data

4. **Data Protection with social media**

Something on the lens-navi privacy policy was that they made explicit the use of social media with the platform they use. They have sections of twitter, youtube, facebook, word press, google analytics.

5. **Data Security** 

Less of an issue because all data is available else where, we aren't sharing patient data and therefore although we should try to be secure, just need to be aware that it is a constant issue with any technical project. 

**Other comments**

Another aspect of this is, if we plan on monetising, even if the app is just providing data and not providing judgement of products to use, if other companies that don't appear in our app get wind, we may find ourselves being contacted by these companies for favouring certain lens companies over others. I think it's a thought down way down the line, but just thinking about that. 

**Useful links on the process of App development** (Has something to say about the legal issues)

https://blog.dashsdk.com/app-store-requirements-for-health-apps/ - Apple's own policy on publish healthcare apps to it's app store.

https://spdload.com/blog/healthcare-app-development/ - Long article on App development for founders

https://citcentoolkit.files.wordpress.com/2018/04/98533_nhs_inn_appdevroad.pdf - NHS South East document on app development steps.

**Seeking Advice** 

1. https://www.baddinosaur.co.uk/healthcare-app-development - Came across this website which has a free consultation offer - They are also based in Edinburgh. Check it out and see what you think.

2. Using freelance platforms (UpWork) for a legal consultation about the legality our App idea, any legal considerations we need to think about prior to distribution. Need for GDPR compliance and clinical opinions... How legal is it to just use the data and offer up removing on request rather than seeking out permission for the use of the data ? May need some help with drawing up web site/app disclaimers surrounding clinical opinions etc....

**Comment by ButtercupUltra** [comment]
Just saw the baddinosaur app, but couldn't find anything about legal advice.  They seem to do the entire app design, I think.

UpWork seems more like it.  Should we first try to contact the IOL Con guys?

**Comment by medic-code** [comment]
I think we should contact the IOL Con guys - regardless of a legal opinion, we need permission to use the data in some way. They may come back to us and say whilst they display this information, it may be the individual companies we have to deal with rather than them. Just something to consider. I mean the other aspect I'm interested in is the fact that they're able to display this information about the lens ? I wonder how they're managing to do that. 

On the one hand we need optimised constants from IOLCon but the other aspect is using the lens properties data from individual companies ? We may need to contact Alcon etc for permission to use their data when we're trying to create a product using that data. 

Once we have optimised constants we can atleast prototype the App I think - At that point we may need to contact individual lens companies.

**Comment by medic-code** [comment]
@ButtercupUltra 

I've been doing some more digging around legal matters. 

I think consulting a lawyer might be a good first start prior to asking the companies ourselves for a couple of reasons as I think we need to think about a couple of things

1. Are we a medical device ? For education I think we would be fine BUT this is a murky area when providing clinical decision support, which is something we might want to do in the future and so need to understand what we need to do to be a compliant medical device if that is the case. 

2. Do we have to abide by GDPR / HIPAA compliance ? I think are using non-personal data which SHOULD be exempt but we need clarity on that simply because it makes the data protection aspects MUCH less horrible in terms of what we do.

3. We need advice on how to approach companies on requesting consent for using data in a professional manner even if its non personal data - That is we might need to be quite specific on WHAT data we want, how we will use it, how will we store it, how will it be secured etc...  and need to think about these things before engaging in those conversations.

Where we seek advice is also need to think about - Mexico ? US based ?

**Comment by medic-code** [comment]
@ButtercupUltra 

Also having asked a friend of mine - We need to be relatively clear on the business case and clinical case if we do end up having a discussion with these companies as well as any data protection issues we need to have good answers for.

**Comment by medic-code** [comment]
@ButtercupUltra 

Was looking through our companies slide deck and found a couple of useful things. Whilst not necessarily developing for NHS gives us some of the criteria we might need to think about. I do hope this is mostly overboard as we're not acting on patient information 

https://www.nhsx.nhs.uk/key-tools-and-info/digital-technology-assessment-criteria-dtac/ - Website to use digital products in NHS - has the standards needed -> I don't think we would need half as much of that but will be useful to know how far or how little we need to go with our app. 

https://www.gov.uk/government/publications/code-of-conduct-for-data-driven-health-and-care-technology/initial-code-of-conduct-for-data-driven-health-and-care-technology - General guidance by the NHS on developing digital apps.

https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.nhsx.nhs.uk%2Fmedia%2Fdocuments%2FDTAC_version_1.0_FINAL_updated_16.04.odt&wdOrigin=BROWSELINK - Criteria for HTAC that developers should look at. I'll have a look at this.

**Comment by medic-code** [comment]
DTAC Notes @ButtercupUltra 

Five areas for Digital Health Technology to be assessed on to be used with the NHS - Good baseline on what we need to consider. 

1. Clinical safety - Validation of medical device classification for what we would be classed with. 
2. Data Protection
3. Technical assurance
 Has a peneration test been done?
4. Interoperatility (How well product exchanges data with other systems)
5. Usability and accessibility

**Comment by medic-code** [comment]
Also see @ButtercupUltra 

https://iclg.com/practice-areas/digital-health-laws-and-regulations/mexico

Very quick read but sounds like Mexican regulation on digital health apps is still pretty new which is good for us. This may be where we should start then. Let me know what you think.

**Comment by medic-code** [comment]
I've added this stuff into monday.com. Put useful links in correct place and split the content into separate tasks.
