### ISSUE TITLE
Confirm viscoelastic fields to be used in the database

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#69]
As discussed yesterday, confirm which information you want to record in the database for viscoelastics.  @ButtercupUltra 

From memory of last night

1. Composition 
2. Viscoelastic property 
3. Brand

Once confirmed can add to form and database to allow you to input the common viscoelastics in the form as noted in other issue.

**Comment by ButtercupUltra** [comment]
Yes, these would be the fields.  Remembering to have a "similar OVD's" at the bottom of the page (OVD = ophthalmic viscosurgical device)

**Comment by medic-code** [comment]
Yep that will be a search query based upon the type of viscoelastic
