### ISSUE TITLE
Icons for the lens

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#7]
Need to sort out icons for the individual lens page -> Seem to remember there being some lens pictures to use perhaps ? Check there isn't any copyright issues associated with them if using them.

**Comment by ButtercupUltra** [comment]
![external-content duckduckgo](https://user-images.githubusercontent.com/90638515/133248804-118c2d24-a5f1-431e-b9a1-9db18b384ac0.png)

**Comment by ButtercupUltra** [comment]
![plate iol](https://user-images.githubusercontent.com/90638515/133248829-9c81bf01-04b0-4403-bfb1-159348421e92.png)

**Comment by ButtercupUltra** [comment]
![ 3 piece](https://user-images.githubusercontent.com/90638515/133248849-4a66e82f-1c08-47ca-9aad-d1ddb2391d49.png)

**Comment by ButtercupUltra** [comment]
![external-content duckduckgo-1](https://user-images.githubusercontent.com/90638515/133248905-c49023b3-377f-4960-9da8-36037c02503b.png)

**Comment by ButtercupUltra** [comment]
we coud use these in the meantime, just to get a taste of it

1 piece
plate
3 piece

**Comment by medic-code** [comment]
Yep, can add the 3 piece one to the alcon just now to see what it looks like.

**Comment by medic-code** [comment]
@ButtercupUltra Just curious about the source of the image ? Incase we do end up using it past the beta phase.

**Comment by medic-code** [comment]
Added the 3 piece to the Alcon IOL. Also added the images to the asset folder for future IOLs currently. 

Are there other IOL images we will need for the Alcon and Zeiss IOLs ? @ButtercupUltra

**Comment by medic-code** [comment]
@ButtercupUltra 

Do we need to think about permission to use these types of images ?

**Comment by ButtercupUltra** [comment]
IOL Con uses the images from each one of the manufactures in their All Lenses table.  I would imagine that, if we were to gain access to their data for display, we could also display the same icons.  If not, we could use the generic ones as above, or design something very similar for a small price.  The IOL image is merely aesthetics and does not provide an additional function (the type of lens will be described with text, anyways).

**Comment by medic-code** [comment]
I've added this information to monday.com will close.
