### ISSUE TITLE
Monetization Model consideration

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#76]
As a digital product thinking about revenue models.  @ButtercupUltra 

Some things to consider ? 

1. In app ads - Completely free but ads shown to users. 
2. Freemium - App is free, but some features can be unlocked by in-app purchases
3. Subscription - Subscription bases, users most pay for a subscription 
4. Paid - Users pay for app with a one time payment. 

Something to consider, not sure that in-app ads makes sense, freemium may not be applicable or wanted as we want to keep this simple in terms of features. Subscription may be possible, but I wonder whether we have enough for this to make sense. Paid once makes some sense but can be quite limiting in getting users through the door to using the app. 

Some thoughts initially would be good to consider. Also if you have any other monetization models that could be used other than these ?

**Comment by ButtercupUltra** [comment]
No idea about monetization...  I agree that the only one that would make sense is subscription and paid.  The subscription could be yearly. I think a monthly suscription would push people away.  

More than in-app adds, we could try get the manufacturers to chip in. If the app suggests, say, Alcon lenses first and we make Alcon more visible, maybe Alcon would pay for that?  Also, could include their lenses in the 'suggested lenses' that we mentioned at some point.  That could be an area for product placement and some revenue may come from it.

**Comment by medic-code** [comment]
A yearly subscription makes some sense 

I think the suggested lenses' aspect is interesting from a business perspective but helps if we have uptake of the app to make that play. Suggested lenses does have some medicolegal aspects to it we would need to navigate.

**Comment by medic-code** [comment]
I've copied this into monday.com now will close this.
