### ISSUE TITLE
Competitive analysis 

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#77]
@ButtercupUltra 
We've talked a little abit about this, but worth doing a bit more research on who are the direct and not so direct competitors ? 

Specifically who are they ? 
What are each products strength ?
What are each products weaknesses ? 

Strengths are what should be as a minimum for our product 
The weaknesses are the areas of opportunity for us.

A list of functionalities and features to improve our app should be the end of this. It may be that there is none that we want to include but we should dive into this.

**Comment by medic-code** [comment]
Direct competitors 

1. Lens navi 
https://www.app4eyes.com/solutions/lens-navi/

In-direct competitors 

I think the websites that have the data could be considered as indirect competitors

1. ULIB 
2. IOL Con 
3. IOL-Calcalator (https://fnd.io/#/us/iphone-app/456304691-iol-calculator-by-columbia-university)
4.  Panacea IOL and Toric Calculator -(http://www.panaceaiolandtoriccalculator.com/)
5. SmartEye
6. Multifocal Lens Analyzer
7. Eye Handbook 
8. Toric Calculator for iPhone

**Comment by ButtercupUltra** [comment]
Taking another look at these, most are calculators.  We are not a calculator.  So we actually offer something completely different.  It's simply a different approach and that is what makes it interesting.  ULIB and IOL Con would be the only ones to provide the data, but they offer the same service, just not in an integrated way.

**Comment by medic-code** [comment]
Yep - agreed. I think I put this up because we need to be seeing what else is out there and what is unique about our product. It does seem there is nothing like what we're attempting to do which feels a little surreal... I do think we should keep this in the back of our minds, can we really be the first to do something like this ?

**Comment by medic-code** [comment]
I've copied this into monday.com and close this issue.
