### ISSUE TITLE
Contact ULIB about data

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#78]
As discussed on the weekend, probably best to email and ask about how we may use the data as first point of call. See issue . Relatively important given we need to get the optimised data from somewhere. I suspect might come better from an ophthalmologist asking and also can't deny you the opportunity to speak to Mr Haigis himself!

@ButtercupUltra

**Comment by medic-code** [comment]
See https://github.com/medic-code/IOL-Assist/issues/68 for more details generally about data.

**Comment by ButtercupUltra** [comment]
draft for letter for Haigis

**Comment by ButtercupUltra** [comment]
Dear Dr,

I hope you are well in this dubious times, seeing as COVID cases are slightly upticking again.  

I write to you from Scotland, where a colleague and I are trying to develop an app to present IOL constants and other data in a practical, approachable, and quick manner by the use of mobile phones.  Our intention is to display data from ULIB so surgeons can have an accesible database for their calculations. We wouldn’t include these data without further consulting with you.

I would be delighted if you wanted to discuss this further.  I hope you can support our thrive for innovation.  

Many thanks.

Dr. Juan Alberto López Ulloa
International Fellow in Ophthalmology
Queen Margaret Hospital
Dumfernline, Scotland
KY12 0SU
+44  (0) 7999 051047

**Comment by medic-code** [comment]
Yep seems fine to me.

**Comment by ButtercupUltra** [comment]
Here

**Comment by ButtercupUltra** [comment]
To _IOL Con_ Team,

I hope you have been keeping well.

I write to you from London, where our team is developing a smart-phone app to present IOL constants and other data in a practical, approachable, and quick way to surgeons working in Europe and overseas. Our intention is to display data from _ULIB / IOL Con_ so surgeons can have an accesible database for their calculations. 

I would be delighted if you wanted to discuss this further. I hope you can support our thrive for innovation.

Many thanks.

Dr. Juan Alberto López Ulloa 
_IOL Assist_ CoFounder
Ophthalmology Fellow, Bart’s Health NHS Trust, London

**Comment by ButtercupUltra** [comment]
Do you think this is enough to send as initial contact?  Should we try just yet or should we wait to have a MVP? We could use nominal a-constants from the original websites for that.

**Comment by medic-code** [comment]
I guess the biggest disappointment would be if they wanted to talk and we
had nothing to show them. Should we wait till we have working MVP but I
think we’d have to use fake data until we have permission. The concept is
more important than the actual data as for as trying to get these people
onboard.

Let me know if you think differently.

**Comment by medic-code** [comment]
I've copied these emails into confluence and added tasks in monday.com.
