### ISSUE TITLE
Viscoelastic Icon

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#80]
Come up with viscoelastic rough design if needed to be can be drawn, or grab icon from web that we can use.

**Comment by ButtercupUltra** [comment]
http://cdn.onlinewebfonts.com/svg/img_5634.png
Roughly.  Cohesives would be green-blue, dispersives would be yellow.  Can use this in the meantime?

**Comment by medic-code** [comment]
Need to check if it's in the public domain before we can use this in a
distributed app. From a technical app perspective any image can be used
though. If you look for the parent website of the image there should be a
terms and conditions page about using images /data from the site or what
license they have.

**Comment by ButtercupUltra** [comment]
https://www.flaticon.com/premium-icon/syringe-needle_5843940?term=needle&page=1&position=29

These are public domain. I think it would be relatively easy to change the color palette?

**Comment by medic-code** [comment]
Yep this could work.

**Comment by medic-code** [comment]
I've copied this to monday.com
