### ISSUE TITLE
Scale up lens for NHS Fife 

### ISSUE THREAD

**Issue by medic-code** [medic-code/IOL-Assist#9]
To input IOL data used in NHS Fife, or at the least show me where the data is.

That is, once happy with the level of data needed on each IOL, to add the IOLs used in NHS Fife to the database. This is to enable users to be able to search by name the IOLs commonly used in NHS Fife and to access the data about each individual IOL.

**Comment by ButtercupUltra** [comment]
NHS Fife uses Alcon mostly.  Zeiss lenses only toric ones.  Pretty confidente we can start with alcon IOLS, mainly:

SN60WF
SN60AT or SA60AT
SN6Atx
MA60MA  or MN60MA
MA60AC
MA30AC

These are enough.  Short and sweet.

**Comment by medic-code** [comment]
Is the list 

SN60WF
SN60AT or SA60AT
SN6Atx
MA60MA or MN60MA
MA60AC
MA30AC

For alcon ? Are they all currently on the spreadsheet you sent me in the email ? 

Do you have the information on the Zeiss lens ?

**Comment by medic-code** [comment]
After discussion. These are for alcon lens. Will add separate issue for inputting Zeiss lens data. Would be good to sort out all lens data fields you want, so I can update the form and then you can test run the form instead of inputting data into a spreadsheet! That way the data ends up in the database.

**Comment by medic-code** [comment]
I think for now we just see if we can use the data - I'll close this issue for now as this may change later on.
